authapp/urls.py
from django.urls import path
from .views import UserLoginView, UserCreateView
from django.contrib.auth.views import LogoutView

app_name = "authapp"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="/auth/login/"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
]

poker_estimation/urls.py
from django.contrib import admin
from django.urls import path, include
from roomapp.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("authapp.urls")),
    path("room/", include("roomapp.urls")),
    path("", HomeView.as_view(), name="home"),
]

authapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

authapp/views.py
from django.contrib.auth.views import LoginView
from django.views.generic import FormView
from .forms import CreateUserForm


class UserLoginView(LoginView):
    template_name = "authapp/login.html"


class UserCreateView(FormView):
    template_name = "authapp/register.html"
    form_class = CreateUserForm
    success_url = "/auth/login/"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

authapp/templates/authapp/login.html
<!-- templates/roomapp/login.html -->
<h2>Login</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Login</button>
</form>
<p>
  Don't have an account?
  <a href="{% url 'authapp:register' %}">Register here</a>
</p>

authapp/templates/authapp/register.html
<h2>Register</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Create User</button>
</form>